export const ICON_OPTIONS = [
  { name: "Zap", label: "Elétrica" },
  { name: "Droplets", label: "Água / Hidráulica" },
  { name: "Trees", label: "Jardim" },
  { name: "Waves", label: "Piscina" },
  { name: "PaintRoller", label: "Pintura" },
  { name: "BrickWall", label: "Construção" },
  { name: "HardHat", label: "Mão de obra" },
  { name: "Sparkles", label: "Limpeza" },
  { name: "Wrench", label: "Manutenção" },
  { name: "ShieldCheck", label: "Segurança" },
  { name: "House", label: "Casa" },
  { name: "Fence", label: "Cerca / Portão" },
  { name: "Lightbulb", label: "Iluminação" },
  { name: "Hammer", label: "Ferramentas" },
  { name: "Car", label: "Transporte" },
  { name: "Leaf", label: "Natureza" },
  { name: "Flame", label: "Sauna / Aquecimento" },
  { name: "Package", label: "Outros" },
] as const;
